ideje = {'Bohinjsko_jezero': ('Gorenjska', 'narava', 'jezero', 'smučišče',
                              'gore', 'slap'),
         'Kranjska_gora': ('Gorenjska', 'smučišče', 'jezero', 'gore', 'narava'),
         'Blejsko_jezero': ('Gorenjska', 'narava', 'jezero', 'grad'),
         'Radovljica' : ('Gorenjska', 'mesto', 'muzeji'),
         'Jesenice' : ('Gorenjska', 'mesto', 'muzeji'),
         'Kropa' : ('Gorenjska', 'muzeji'),
         'Triglavski_narodni_park' : ('Gorenjska', 'narava', 'gore'),
         'dolina_Vrata': ('Gorenjska', 'narava', 'slap', 'gore'),
         'Kranj' : ('Gorenjska', 'mesto', 'muzeji'),
         'Škofja_Loka' : ('Gorenjska', 'mesto', 'muzeji', 'grad'),
         'Ljubljana': ('Notranjska', 'mesto', 'muzeji'),
         'Piran': ('Primorska', 'morje', 'mesto'),
         'Koper' : ('Primorska', 'morje', 'mesto'),
         'Portorož' : ('Primorska', 'morje', 'mesto'),
         'Kraški_rob' : ('Primorska', 'narava'),
         'Škocjanske_jame' : ('Primorska', 'narava', 'jama'),
         'Postojnska_jama' : ('Primorska', 'narava', 'jama'),
         'Moravske_toplice': ('Prekmurje', 'terme'),
         'Lendava': ('Prekmurje', 'mesto', 'terme')}
